# docker-compose.yml (Fuente Única de Configuración)
services:
  derper:
    image: ghcr.io/tomasmetal23/derper:latest
    container_name: tailscale-derper
    restart: unless-stopped

    ports:
      - "3478:3478/udp"
      - "8443:443/tcp"

    volumes:
      - /home/saiyans/stacks/traefik_podman/output/*.saiyans.com.ve:/certs:ro  

    # Aquí está TODA la configuración del servidor. Un solo lugar.
    environment:
      # La clave secreta, la razón de todo este viaje.
      - DERP_PRIVATE_KEY=private_key:

      # Configuración del servidor
      - DERP_HOSTNAME=derp.saiyans.com.ve
      - DERP_ADDR=:443

      # Configuración de los certificados
      - DERP_CERT_MODE=manual
      - DERP_CERT_DIR=/certs

      # Configuración de seguridad (recomendado)
      - DERP_VERIFY_CLIENTS=false