services:
  derper:
    image: ghcr.io/tomasmetal23/derper:latest
    container_name: tailscale-derper
    restart: unless-stopped
    ports:
      - "3478:3478/udp"
      - "8443:443/tcp"
    volumes:
      - derper-data:/home/derper/data
      - /home/saiyans/stacks/traefik_podman/output/*.saiyans.com.ve:/certs:ro  
    environment:
      - DERP_HOSTNAME=derp.saiyans.com.ve
      - DERP_ADDR=:443
      - DERP_STUN_PORT=3478
      - DERP_VERIFY_CLIENTS=true
volumes:
  derper-data: