# docker-compose.yml (Versión Final con Volumen Persistente)

version: "3.8"

services:
  derper:
    image: ghcr.io/tomasmetal23/derper:latest
    container_name: tailscale-derper
    restart: unless-stopped

    ports:
      - "3478:3478/udp" # Puerto STUN
      - "8443:443/tcp"  # Puerto DERP (HTTPS)

    volumes:
      - /home/saiyans/stacks/traefik_podman/output/*.saiyans.com.ve:/certs:ro  
      - derper-data:/home/derper/data

    environment:
      # --- Configuración del Servidor ---
      - DERP_HOSTNAME=derp.saiyans.com.ve
      - DERP_ADDR=:443
      - DERP_CERT_MODE=manual
      - DERP_CERT_DIR=/certs
      - DERP_STUN_PORT=3478
      # NOTA: Ya no necesitamos DERP_PRIVATE_KEY aquí. 
      # El script se encarga de todo.

# --- DEFINICIÓN DEL VOLUMEN ---
# Aquí se declara el volumen con nombre que usará el servicio.
volumes:
  derper-data: