services:
  derper:
    image: ghcr.io/tomasmetal23/derper:latest
    container_name: tailscale-derper
    restart: unless-stopped

    ports:
      - "3478:3478/udp"
      - "8443:443/tcp"

    volumes:
      - /home/saiyans/stacks/traefik_podman/output/*.saiyans.com.ve:/certs:ro  
      - derper_data:/home/derper/.cache/tailscale/derper         

    environment:
      DERP_ADDR: ":443"                 
      DERP_HOSTNAME: "derp.saiyans.com.ve"    
      DERP_STUN: "true"                    
      DERP_STUN_PORT: "3478"                  
      DERP_HTTPS_PORT: "-1"                    
      DERP_CERTMODE: "manual"                  
      DERP_CERTDIR: "/certs"                  
    
volumes:
  derper_data:
    driver: local