# docker-compose.yml (Fuente Única de Configuración COMPLETA)

version: "3.8"

services:
  derper:
    image: ghcr.io/tomasmetal23/derper:latest
    container_name: tailscale-derper
    restart: unless-stopped

    ports:
      - "3478:3478/udp"
      - "8443:443/tcp"

    volumes:
      - /home/saiyans/stacks/traefik_podman/output/*.saiyans.com.ve:/certs:ro  

    # Aquí está TODA la configuración, sin omitir nada.
    environment:
      # --- Configuración de Identidad y Red ---
      - DERP_PRIVATE_KEY=private_key:
      - DERP_HOSTNAME=derp.saiyans.com.ve
      - DERP_ADDR=:443

      # --- Configuración de Certificados ---
      - DERP_CERT_MODE=manual
      - DERP_CERT_DIR=/certs

      # --- ¡AQUÍ ESTÁ LO QUE FALTABA! ---
      # Activa el servidor STUN. Equivale a -stun=true
      - DERP_STUN=true
      # Desactiva el servidor HTTP en el puerto 80. Equivale a -http-port=-1
      - DERP_HTTP_PORT=-1

      # --- Configuración de Seguridad ---
      # Equivale a -verify-clients=true (o false si así lo prefieres)
      - DERP_VERIFY_CLIENTS=true